# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

# DU. Configure the application for Twilio SMS
development:
  secret_key_base: 71f4f296b5bf621cdd1638f2110d4f55fa09a3f0eae8259385996a61ddde863d08bc6c3e421d9bbbb06d1ef1a899f10738a9e50d3c6b12b9b236d170241bb30d
  twilio_account_sid:  <%= ENV.fetch("SECRET_KEY_BASE", "ACef4810ee49e6bde28a1dbf6db131b023") %>
  twilio_auth_token:  <%= ENV.fetch("SECRET_KEY_BASE", "28b4c42de4a07887cd1d29ee53d2a100") %>
  twilio_phone_number:  <%= ENV.fetch("SECRET_KEY_BASE", "19782881673") %>
 
test:
  secret_key_base: b9042fc96c500df930be5888c50a9e459ea16c2de4fdf04ad36770a76ce2dd1b1293c1e4ae97043c4468313af604bac2a2c7dfe82102a12e90e7c3c458d23760
  twilio_account_sid:  <%= ENV.fetch("SECRET_KEY_BASE", "ACef4810ee49e6bde28a1dbf6db131b023") %>
  twilio_auth_token:  <%= ENV.fetch("SECRET_KEY_BASE", "28b4c42de4a07887cd1d29ee53d2a100") %>
  twilio_phone_number:  <%= ENV.fetch("SECRET_KEY_BASE", "19782881673") %>
 


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
